import SwiftUI

struct SettingsView: View {
    @Environment(\.dismiss) private var dismiss; @AppStorage("isLoggedIn") private var isLoggedIn = false; @AppStorage("viewMode") private var viewMode = ViewMode.automatic.rawValue; @AppStorage("customAccentHex") private var customAccentHex = "#007AFF"; @AppStorage("appTheme") private var appTheme = AppTheme.system.rawValue; @Binding var categories: [StreamCategory]; let accentColor: Color; @ObservedObject var viewModel: ChannelViewModel; let onSave: () -> Void
    @AppStorage("xstreamURL") private var xstreamURL = ""; @AppStorage("username") private var username = ""; @AppStorage("password") private var password = "";
    var body: some View { NavigationStack { Form { Section(header: Text("Appearance")) { Picker("Theme", selection: $appTheme) { ForEach(AppTheme.allCases) { t in Text(t.rawValue).tag(t.rawValue) } }.pickerStyle(.segmented); Picker("Layout Mode", selection: $viewMode) { ForEach(ViewMode.allCases, id: \.rawValue) { Text($0.rawValue).tag($0.rawValue) } }.pickerStyle(.segmented); ColorPicker("App Accent Color", selection: Binding(get: { Color(hex: customAccentHex) ?? .blue }, set: { if let h = $0.toHex() { customAccentHex = h } })) }; NebulaSettingsSection(); Section(header: Text("Content Management")) {
        Button(action: {
            dismiss()
            Task { if let url = URL(string: xstreamURL) { await viewModel.updateEPG(baseURL: url, user: username, pass: password) } }
        }) {
            HStack { Label("Manual Guide Update", systemImage: "arrow.clockwise.icloud"); Spacer(); if viewModel.isUpdatingEPG { ProgressView().tint(.gray) } }
        }.disabled(viewModel.isUpdatingEPG)
        NavigationLink(destination: CategoriesManagerView(categories: $categories, accentColor: accentColor, viewModel: viewModel)) { Label("Manage Categories", systemImage: "list.bullet.rectangle.portrait.fill") }; NavigationLink(destination: HiddenChannelsSettingsView(viewModel: viewModel)) { HStack { Label("Hidden Channels", systemImage: "eye.slash.fill").foregroundColor(.red); Spacer(); if !viewModel.hiddenIDs.isEmpty { Text("\(viewModel.hiddenIDs.count)").foregroundStyle(.secondary) } } } }; Section(header: Text("Support")) { Link(destination: URL(string: "https://discord.gg/QkBUjsGCJ2")!) { Label("Join Discord", systemImage: "bubble.left.and.bubble.right.fill") }; Link(destination: URL(string: "https://buymeacoffee.com/mongoosemonke")!) { Label("Buy Me a Coffee", systemImage: "cup.and.saucer.fill") } }; Section { Button("Logout", role: .destructive) { withAnimation { viewModel.reset(); isLoggedIn = false } } } }.scrollIndicators(.hidden).navigationTitle("Settings").toolbar { ToolbarItem(placement: .topBarTrailing) { Button("Done") { onSave(); dismiss() } } } } }
}

struct CategoriesManagerView: View {
    @Binding var categories: [StreamCategory]; let accentColor: Color; @ObservedObject var viewModel: ChannelViewModel; @State private var categoryToRename: StreamCategory?; @State private var localRenameName = ""; @State private var showLocalRenameAlert = false
    var body: some View { List { Section { Button(action: { categories.indices.forEach { categories[$0].isHidden = false } }) { Label("Show All Categories", systemImage: "eye") }; Button(action: { categories.indices.forEach { categories[$0].isHidden = true } }) { Label("Hide All Categories", systemImage: "eye.slash") } }; Section(header: Text("Drag to Reorder"), footer: Text("Tap eye icon to toggle visibility. Long press to rename.")) { ForEach($categories) { $cat in HStack { Button(action: { withAnimation { cat.isHidden.toggle() } }) { Image(systemName: cat.isHidden ? "eye.slash" : "eye").foregroundColor(cat.isHidden ? .gray : accentColor).frame(width: 30) }.buttonStyle(.plain); Text(cat.name).foregroundStyle(cat.isHidden ? .secondary : .primary).strikethrough(cat.isHidden); Spacer() }.contextMenu { Button { categoryToRename = cat; localRenameName = cat.name; showLocalRenameAlert = true } label: { Label("Rename", systemImage: "pencil") } } }.onMove { src, dst in categories.move(fromOffsets: src, toOffset: dst); for i in 0..<categories.count { categories[i].order = i } } } }.environment(\.editMode, .constant(.active)).navigationTitle("Categories").alert("Rename Category", isPresented: $showLocalRenameAlert) { TextField("Name", text: $localRenameName); Button("Save") { if let c = categoryToRename { viewModel.renameCategory(id: c.id, newName: localRenameName) } }; Button("Cancel", role: .cancel) {} } }
}
struct HiddenChannelsSettingsView: View {
    @ObservedObject var viewModel: ChannelViewModel; @State private var searchText = ""
    var hidden: [StreamChannel] { let h = viewModel.channels.filter { viewModel.hiddenIDs.contains($0.id) }; if searchText.isEmpty { return h }; return h.filter { $0.name.localizedCaseInsensitiveContains(searchText) } }
    var body: some View { List { if viewModel.hiddenIDs.isEmpty { Section { Text("No hidden channels").foregroundColor(.secondary).frame(maxWidth: .infinity, alignment: .center).padding() } } else { Section(header: Text("Hidden Channels (\(hidden.count))")) { ForEach(hidden) { c in HStack { CachedAsyncImage(urlString: c.icon ?? "", size: CGSize(width: 30, height: 30)).frame(width: 30, height: 30).cornerRadius(4); Text(c.name).lineLimit(1); Spacer(); Button("Unhide") { withAnimation { viewModel.unhideChannel(c.id) } }.buttonStyle(.bordered).tint(.blue).controlSize(.small) } } } } }.searchable(text: $searchText, prompt: "Search hidden channels").navigationTitle("Hidden Channels").toolbar { if !viewModel.hiddenIDs.isEmpty { ToolbarItem(placement: .topBarTrailing) { Button("Unhide All") { withAnimation { viewModel.hiddenIDs.forEach { viewModel.unhideChannel($0) } } } } } } }
}

struct NebulaSettingsSection: View {
    @AppStorage("nebColor1") private var nebColor1 = "#AF52DE"; @AppStorage("nebColor2") private var nebColor2 = "#007AFF"; @AppStorage("nebColor3") private var nebColor3 = "#FF2D55"; @AppStorage("nebX1") private var nebX1 = 0.2; @AppStorage("nebY1") private var nebY1 = 0.2; @AppStorage("nebX2") private var nebX2 = 0.8; @AppStorage("nebY2") private var nebY2 = 0.3; @AppStorage("nebX3") private var nebX3 = 0.5; @AppStorage("nebY3") private var nebY3 = 0.8
    var body: some View { Section(header: Text("Interactive Nebula Editor")) { HStack { Spacer(); ZStack { NebulaBackgroundView(color1: Color(hex: nebColor1) ?? .purple, color2: Color(hex: nebColor2) ?? .blue, color3: Color(hex: nebColor3) ?? .pink, point1: UnitPoint(x: nebX1, y: nebY1), point2: UnitPoint(x: nebX2, y: nebY2), point3: UnitPoint(x: nebX3, y: nebY3)).clipShape(RoundedRectangle(cornerRadius: 12)).overlay(RoundedRectangle(cornerRadius: 12).stroke(Color.white.opacity(0.2), lineWidth: 1)); GeometryReader { geo in DragHandle(x: $nebX1, y: $nebY1, color: Color(hex: nebColor1) ?? .purple, size: geo.size); DragHandle(x: $nebX2, y: $nebY2, color: Color(hex: nebColor2) ?? .blue, size: geo.size); DragHandle(x: $nebX3, y: $nebY3, color: Color(hex: nebColor3) ?? .pink, size: geo.size) } }.frame(width: 200, height: 200 * (16/9)).padding(.vertical, 10); Spacer() }.listRowBackground(Color.clear); ColorPicker("Aura 1 Color", selection: Binding(get: { Color(hex: nebColor1) ?? .blue }, set: { if let h = $0.toHex() { nebColor1 = h } })); ColorPicker("Aura 2 Color", selection: Binding(get: { Color(hex: nebColor2) ?? .blue }, set: { if let h = $0.toHex() { nebColor2 = h } })); ColorPicker("Aura 3 Color", selection: Binding(get: { Color(hex: nebColor3) ?? .blue }, set: { if let h = $0.toHex() { nebColor3 = h } })); Button("Reset to Defaults") { nebColor1 = "#AF52DE"; nebColor2 = "#007AFF"; nebColor3 = "#FF2D55"; nebX1 = 0.2; nebY1 = 0.2; nebX2 = 0.8; nebY2 = 0.3; nebX3 = 0.5; nebY3 = 0.8 }.foregroundStyle(.red) } }
}
struct DragHandle: View { @Binding var x: Double; @Binding var y: Double; let color: Color; let size: CGSize; var body: some View { Circle().fill(color).frame(width: 30, height: 30).overlay(Circle().stroke(Color.white, lineWidth: 2)).shadow(radius: 4).position(x: x * size.width, y: y * size.height).gesture(DragGesture().onChanged { v in x = min(max(v.location.x / size.width, 0), 1); y = min(max(v.location.y / size.height, 0), 1) }) } }
